apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deployment
  labels:
    app: restapi
spec:
  selector:
    matchLabels:
      app: restapi
  replicas: 2
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
        - name: restapi
          image: nischal200/containersolution-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
        - name: db
          image: mariadb:10.3
          env:
             - name: MYSQL_DATABASE
               value: "Titanic"
             - name: MYSQL_ROOT_PASSWORD
               value: "rikesh"
          imagePullPolicy: Always
          ports:
             - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: restapi
  #externalIPs:
    #- 80.11.12.10
  ports:  
    - protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: 31000
  type: LoadBalancer 
