apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auditing-service
      tier: backend
      environment: integration
  template:
    metadata:
      labels:
        app: auditing-service
        tier: backend
        environment: integration
    spec:
      containers:
        - name: app
          image: nischal200/containersolution-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          # args: 
          #   - /bin/sh
          #   - sleep 3000

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: "Titanic"
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: "rikesh"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
